// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.0
// source: dice.proto

package dice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 摇骰子回复
type ShakeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID     int64 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`         // 用户编号
	DicePoints int32 `protobuf:"varint,2,opt,name=DicePoints,proto3" json:"DicePoints,omitempty"` // 骰子点数
}

func (x *ShakeResponse) Reset() {
	*x = ShakeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShakeResponse) ProtoMessage() {}

func (x *ShakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShakeResponse.ProtoReflect.Descriptor instead.
func (*ShakeResponse) Descriptor() ([]byte, []int) {
	return file_dice_proto_rawDescGZIP(), []int{0}
}

func (x *ShakeResponse) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ShakeResponse) GetDicePoints() int32 {
	if x != nil {
		return x.DicePoints
	}
	return 0
}

// 场景通知
type SceneNotice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   bool            `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`                                                                                      // 状态是否游戏中
	LeftTime int64           `protobuf:"varint,2,opt,name=LeftTime,proto3" json:"LeftTime,omitempty"`                                                                                  // 切换状态剩余时间用于倒计时
	Dice     map[int64]int32 `protobuf:"bytes,3,rep,name=Dice,proto3" json:"Dice,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` // 用户编号骰子点数，值为0表示游戏中不能看到他人已摇到的点数
}

func (x *SceneNotice) Reset() {
	*x = SceneNotice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SceneNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneNotice) ProtoMessage() {}

func (x *SceneNotice) ProtoReflect() protoreflect.Message {
	mi := &file_dice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneNotice.ProtoReflect.Descriptor instead.
func (*SceneNotice) Descriptor() ([]byte, []int) {
	return file_dice_proto_rawDescGZIP(), []int{1}
}

func (x *SceneNotice) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *SceneNotice) GetLeftTime() int64 {
	if x != nil {
		return x.LeftTime
	}
	return 0
}

func (x *SceneNotice) GetDice() map[int64]int32 {
	if x != nil {
		return x.Dice
	}
	return nil
}

// 结算通知
type SettlementNotice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdleDuration int64           `protobuf:"varint,1,opt,name=IdleDuration,proto3" json:"IdleDuration,omitempty"`                                                                          // 空闲时长
	Winner       []int64         `protobuf:"varint,2,rep,packed,name=Winner,proto3" json:"Winner,omitempty"`                                                                               // 多个赢家
	Dice         map[int64]int32 `protobuf:"bytes,3,rep,name=Dice,proto3" json:"Dice,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` // 用户编号骰子点数
}

func (x *SettlementNotice) Reset() {
	*x = SettlementNotice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SettlementNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementNotice) ProtoMessage() {}

func (x *SettlementNotice) ProtoReflect() protoreflect.Message {
	mi := &file_dice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementNotice.ProtoReflect.Descriptor instead.
func (*SettlementNotice) Descriptor() ([]byte, []int) {
	return file_dice_proto_rawDescGZIP(), []int{2}
}

func (x *SettlementNotice) GetIdleDuration() int64 {
	if x != nil {
		return x.IdleDuration
	}
	return 0
}

func (x *SettlementNotice) GetWinner() []int64 {
	if x != nil {
		return x.Winner
	}
	return nil
}

func (x *SettlementNotice) GetDice() map[int64]int32 {
	if x != nil {
		return x.Dice
	}
	return nil
}

var File_dice_proto protoreflect.FileDescriptor

var file_dice_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x64, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x64, 0x69,
	0x63, 0x65, 0x22, 0x47, 0x0a, 0x0d, 0x53, 0x68, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x44,
	0x69, 0x63, 0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x44, 0x69, 0x63, 0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0xab, 0x01, 0x0a, 0x0b,
	0x53, 0x63, 0x65, 0x6e, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x65, 0x66, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x4c, 0x65, 0x66, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x2f, 0x0a, 0x04, 0x44, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x64, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65,
	0x2e, 0x44, 0x69, 0x63, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x44, 0x69, 0x63, 0x65,
	0x1a, 0x37, 0x0a, 0x09, 0x44, 0x69, 0x63, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xbd, 0x01, 0x0a, 0x10, 0x53, 0x65,
	0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x12, 0x22,
	0x0a, 0x0c, 0x49, 0x64, 0x6c, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x49, 0x64, 0x6c, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x57, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x03, 0x52, 0x06, 0x57, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x04, 0x44, 0x69,
	0x63, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x64, 0x69, 0x63, 0x65, 0x2e,
	0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65,
	0x2e, 0x44, 0x69, 0x63, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x44, 0x69, 0x63, 0x65,
	0x1a, 0x37, 0x0a, 0x09, 0x44, 0x69, 0x63, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x61, 0x6e, 0x73, 0x68, 0x69, 0x71, 0x75,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x64, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dice_proto_rawDescOnce sync.Once
	file_dice_proto_rawDescData = file_dice_proto_rawDesc
)

func file_dice_proto_rawDescGZIP() []byte {
	file_dice_proto_rawDescOnce.Do(func() {
		file_dice_proto_rawDescData = protoimpl.X.CompressGZIP(file_dice_proto_rawDescData)
	})
	return file_dice_proto_rawDescData
}

var file_dice_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_dice_proto_goTypes = []interface{}{
	(*ShakeResponse)(nil),    // 0: dice.ShakeResponse
	(*SceneNotice)(nil),      // 1: dice.SceneNotice
	(*SettlementNotice)(nil), // 2: dice.SettlementNotice
	nil,                      // 3: dice.SceneNotice.DiceEntry
	nil,                      // 4: dice.SettlementNotice.DiceEntry
}
var file_dice_proto_depIdxs = []int32{
	3, // 0: dice.SceneNotice.Dice:type_name -> dice.SceneNotice.DiceEntry
	4, // 1: dice.SettlementNotice.Dice:type_name -> dice.SettlementNotice.DiceEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dice_proto_init() }
func file_dice_proto_init() {
	if File_dice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShakeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SceneNotice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SettlementNotice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dice_proto_goTypes,
		DependencyIndexes: file_dice_proto_depIdxs,
		MessageInfos:      file_dice_proto_msgTypes,
	}.Build()
	File_dice_proto = out.File
	file_dice_proto_rawDesc = nil
	file_dice_proto_goTypes = nil
	file_dice_proto_depIdxs = nil
}
