apiVersion: v1
kind: Service
metadata:
  name: gate
spec:
  ports:
  - port: 60006
  selector:
    app: gate
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gate
  template:
    metadata:
      labels:
        app: gate
    spec:
      containers:
      - image: panshiqu/gate_server:1.2
        name: gate
        env:
        # kubectl create secret generic jwt --from-literal=key=ZGVmYXVsdF9rZXk=
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: jwt
              key: key
        ports:
        - containerPort: 60006
